//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace httpscert.src {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("httpscert.src.LangRes", typeof(LangRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] bc {
            get {
                object obj = ResourceManager.GetObject("bc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 × 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter one domain or IP address per line. 的本地化字符串。
        /// </summary>
        internal static string DomainTip {
            get {
                return ResourceManager.GetString("DomainTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入域名或IP地址，每行一个。 的本地化字符串。
        /// </summary>
        internal static string DomainTipCN {
            get {
                return ResourceManager.GetString("DomainTipCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 的本地化字符串。
        /// </summary>
        internal static string Gen {
            get {
                return ResourceManager.GetString("Gen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成 的本地化字符串。
        /// </summary>
        internal static string GenCN {
            get {
                return ResourceManager.GetString("GenCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load: {0} - v{1}
        /// 的本地化字符串。
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — 的本地化字符串。
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password: 的本地化字符串。
        /// </summary>
        internal static string Pwd {
            get {
                return ResourceManager.GetString("Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码: 的本地化字符串。
        /// </summary>
        internal static string PwdCN {
            get {
                return ResourceManager.GetString("PwdCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ? 的本地化字符串。
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save the certificate in... 的本地化字符串。
        /// </summary>
        internal static string SaveTo {
            get {
                return ResourceManager.GetString("SaveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将证书保存到... 的本地化字符串。
        /// </summary>
        internal static string SaveToCN {
            get {
                return ResourceManager.GetString("SaveToCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully created. 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建成功 的本地化字符串。
        /// </summary>
        internal static string SuccessCN {
            get {
                return ResourceManager.GetString("SuccessCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Https Cert Generator - by lalaki.cn
        ///
        ///    -d domain
        ///    -p password\\t(optional)
        ///    -y years\\t(optional) default: 1
        ///
        ///Example: .\httpscert -d localhost -p password -y 2
        /// 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid for 的本地化字符串。
        /// </summary>
        internal static string ValidFor {
            get {
                return ResourceManager.GetString("ValidFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期 的本地化字符串。
        /// </summary>
        internal static string ValidForCN {
            get {
                return ResourceManager.GetString("ValidForCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Https Cert Generator 的本地化字符串。
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Https 证书生成器 的本地化字符串。
        /// </summary>
        internal static string WindowTitleCN {
            get {
                return ResourceManager.GetString("WindowTitleCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 years 的本地化字符串。
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        internal static string YearsCN {
            get {
                return ResourceManager.GetString("YearsCN", resourceCulture);
            }
        }
    }
}
